# Generated by Django 4.1.2 on 2023-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
